-- 021_attendance_leave_rta.sql
-- Package C: Attendance Reconciliation, Leave Staffing Impact,
--            Adherence/Shrinkage Alerts, Payroll-Readiness Outputs.
-- Additive only. Do not execute on production without explicit approval.
USE mas_hrms;

-- ── 1. Attendance Reconciliation ──────────────────────────────────────────────
-- One row per employee per roster_date. Generated by reconciliation service
-- comparing wfm_roster_assignment against wfm_attendance_session.

CREATE TABLE IF NOT EXISTS attendance_reconciliation_record (
  id                   CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  employee_id          CHAR(36)     NOT NULL,
  roster_date          DATE         NOT NULL,
  roster_cycle_id      CHAR(36),
  -- Planned values from roster
  planned_shift_start  TIME,
  planned_shift_end    TIME,
  required_minutes     INT          NOT NULL DEFAULT 0,
  -- Actual values from attendance session
  actual_login_time    DATETIME,
  actual_logout_time   DATETIME,
  actual_minutes       INT          NOT NULL DEFAULT 0,
  break_minutes        INT          NOT NULL DEFAULT 0,
  productive_minutes   INT          NOT NULL DEFAULT 0,
  -- Derived outcomes
  attendance_status    ENUM('present','absent','half_day','late','early_exit',
                            'leave_approved','holiday','week_off','unreconciled')
                                    NOT NULL DEFAULT 'unreconciled',
  adherence_pct        DECIMAL(5,2) NOT NULL DEFAULT 0,
  late_by_minutes      INT          NOT NULL DEFAULT 0,
  early_exit_minutes   INT          NOT NULL DEFAULT 0,
  -- Regularisation link
  regularization_id    CHAR(36),
  -- Audit
  reconciled_at        DATETIME,
  reconciled_by        CHAR(36),
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_recon_emp_date (employee_id, roster_date),
  INDEX idx_recon_date (roster_date),
  INDEX idx_recon_status (attendance_status),
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

-- ── 2. Leave Staffing Impact ──────────────────────────────────────────────────
-- Records impact of approved leaves on roster coverage per process/branch/date.

CREATE TABLE IF NOT EXISTS leave_roster_impact (
  id                   CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  leave_request_id     CHAR(36)     NOT NULL,
  employee_id          CHAR(36)     NOT NULL,
  impact_date          DATE         NOT NULL,
  process_id           CHAR(36),
  branch_id            CHAR(36),
  -- Required vs available headcount on this date
  required_hc          INT          NOT NULL DEFAULT 0,
  planned_hc           INT          NOT NULL DEFAULT 0,
  leave_count          INT          NOT NULL DEFAULT 1,
  coverage_after_leave INT          NOT NULL DEFAULT 0,
  coverage_pct         DECIMAL(5,2) NOT NULL DEFAULT 0,
  -- Risk level for this date
  impact_level         ENUM('none','low','medium','high','critical') NOT NULL DEFAULT 'none',
  -- Was a substitute rostered?
  substitute_rostered  TINYINT(1)   NOT NULL DEFAULT 0,
  substitute_emp_id    CHAR(36),
  notes                TEXT,
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_leave_impact (leave_request_id, impact_date),
  INDEX idx_li_date (impact_date),
  INDEX idx_li_process (process_id),
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

-- ── 3. Adherence Alert ────────────────────────────────────────────────────────
-- Fired when adherence, no-show, break breach or coverage thresholds breached.

CREATE TABLE IF NOT EXISTS adherence_alert (
  id                   CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  alert_date           DATE         NOT NULL,
  alert_type           ENUM('no_show','late_arrival','early_exit','break_breach',
                            'low_adherence','coverage_breach','shrinkage_spike')
                                    NOT NULL,
  severity             ENUM('info','warning','critical') NOT NULL DEFAULT 'warning',
  -- Scope
  employee_id          CHAR(36),
  process_id           CHAR(36),
  branch_id            CHAR(36),
  -- Details
  threshold_pct        DECIMAL(5,2),
  actual_pct           DECIMAL(5,2),
  breach_minutes       INT,
  -- Linked records
  recon_id             CHAR(36),
  coverage_snapshot_id CHAR(36),
  -- Resolution
  status               ENUM('open','acknowledged','resolved','suppressed')
                                    NOT NULL DEFAULT 'open',
  acknowledged_by      CHAR(36),
  acknowledged_at      DATETIME,
  resolved_by          CHAR(36),
  resolved_at          DATETIME,
  resolution_note      TEXT,
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_alert_date (alert_date),
  INDEX idx_alert_type (alert_type),
  INDEX idx_alert_status (status),
  INDEX idx_alert_employee (employee_id),
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

-- ── 4. Shrinkage Daily Snapshot ───────────────────────────────────────────────
-- Per-process/branch daily planned vs unplanned shrinkage calculation.

CREATE TABLE IF NOT EXISTS shrinkage_daily_snapshot (
  id                   CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  snapshot_date        DATE         NOT NULL,
  process_id           CHAR(36),
  branch_id            CHAR(36),
  -- Headcount
  rostered_hc          INT          NOT NULL DEFAULT 0,
  present_hc           INT          NOT NULL DEFAULT 0,
  absent_hc            INT          NOT NULL DEFAULT 0,
  on_leave_hc          INT          NOT NULL DEFAULT 0,
  late_count           INT          NOT NULL DEFAULT 0,
  -- Shrinkage breakdown
  planned_shrinkage_pct   DECIMAL(5,2) NOT NULL DEFAULT 0,  -- leaves + approved off
  unplanned_shrinkage_pct DECIMAL(5,2) NOT NULL DEFAULT 0,  -- no-shows + unapproved
  total_shrinkage_pct     DECIMAL(5,2) NOT NULL DEFAULT 0,
  -- Adherence aggregate
  avg_adherence_pct    DECIMAL(5,2) NOT NULL DEFAULT 0,
  avg_productive_mins  INT          NOT NULL DEFAULT 0,
  total_break_mins     INT          NOT NULL DEFAULT 0,
  break_breach_count   INT          NOT NULL DEFAULT 0,
  -- Payroll readiness
  attendance_locked    TINYINT(1)   NOT NULL DEFAULT 0,
  locked_at            DATETIME,
  locked_by            CHAR(36),
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_shr_date_proc (snapshot_date, process_id, branch_id),
  INDEX idx_shr_date (snapshot_date),
  FOREIGN KEY (process_id) REFERENCES process_master(id) ON DELETE SET NULL,
  FOREIGN KEY (branch_id)  REFERENCES branch_master(id)  ON DELETE SET NULL
);

-- ── 5. Payroll-Readiness Flag ─────────────────────────────────────────────────
-- Per-employee per-roster-cycle payroll-input-readiness signal.
-- Set after attendance is locked and reconciliation passes threshold.

CREATE TABLE IF NOT EXISTS payroll_readiness_flag (
  id                   CHAR(36)     NOT NULL DEFAULT (UUID()) PRIMARY KEY,
  employee_id          CHAR(36)     NOT NULL,
  roster_cycle_id      CHAR(36),
  period_start         DATE         NOT NULL,
  period_end           DATE         NOT NULL,
  -- Attendance summary for payroll input
  working_days         INT          NOT NULL DEFAULT 0,
  present_days         INT          NOT NULL DEFAULT 0,
  absent_days          INT          NOT NULL DEFAULT 0,
  leave_days           INT          NOT NULL DEFAULT 0,
  half_days            INT          NOT NULL DEFAULT 0,
  lwp_days             DECIMAL(4,1) NOT NULL DEFAULT 0,
  total_productive_mins INT         NOT NULL DEFAULT 0,
  -- Status
  status               ENUM('pending','ready','sent_to_payroll','processed')
                                    NOT NULL DEFAULT 'pending',
  readiness_notes      TEXT,
  flagged_at           DATETIME,
  flagged_by           CHAR(36),
  sent_at              DATETIME,
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pr_flag (employee_id, period_start),
  INDEX idx_pr_status (status),
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);
