CREATE TABLE IF NOT EXISTS salary_increment_request (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  employee_id CHAR(36) NOT NULL,
  current_assignment_id CHAR(36) DEFAULT NULL,
  current_ctc DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  proposed_ctc DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  increment_percentage DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
  effective_from DATE NOT NULL,
  reason_code VARCHAR(80) DEFAULT NULL,
  reason TEXT DEFAULT NULL,
  business_justification TEXT DEFAULT NULL,
  requested_by CHAR(36) NOT NULL,
  requested_role VARCHAR(80) DEFAULT NULL,
  hr_validated_by CHAR(36) DEFAULT NULL,
  hr_validated_at DATETIME DEFAULT NULL,
  finance_validated_by CHAR(36) DEFAULT NULL,
  finance_validated_at DATETIME DEFAULT NULL,
  approved_by CHAR(36) DEFAULT NULL,
  approved_at DATETIME DEFAULT NULL,
  rejected_by CHAR(36) DEFAULT NULL,
  rejected_at DATETIME DEFAULT NULL,
  implemented_by CHAR(36) DEFAULT NULL,
  implemented_at DATETIME DEFAULT NULL,
  new_assignment_id CHAR(36) DEFAULT NULL,
  communication_status ENUM('pending','queued','sent','failed','not_required') NOT NULL DEFAULT 'pending',
  letter_status ENUM('pending','generated','released','acknowledged','not_required') NOT NULL DEFAULT 'pending',
  status ENUM('draft','submitted','hr_validated','finance_validated','approved','rejected','implemented','cancelled') NOT NULL DEFAULT 'submitted',
  remarks TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_increment_employee (employee_id, status),
  KEY idx_increment_effective (effective_from, status),
  KEY idx_increment_requested_by (requested_by),
  CONSTRAINT fk_increment_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  CONSTRAINT fk_increment_current_assignment FOREIGN KEY (current_assignment_id) REFERENCES employee_salary_assignment(id) ON DELETE SET NULL,
  CONSTRAINT fk_increment_new_assignment FOREIGN KEY (new_assignment_id) REFERENCES employee_salary_assignment(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salary_increment_audit_log (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  request_id CHAR(36) NOT NULL,
  event_type VARCHAR(80) NOT NULL,
  old_status VARCHAR(80) DEFAULT NULL,
  new_status VARCHAR(80) DEFAULT NULL,
  old_value JSON DEFAULT NULL,
  new_value JSON DEFAULT NULL,
  actor_user_id CHAR(36) DEFAULT NULL,
  actor_role VARCHAR(80) DEFAULT NULL,
  remarks TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_increment_audit_request (request_id, created_at),
  CONSTRAINT fk_increment_audit_request FOREIGN KEY (request_id) REFERENCES salary_increment_request(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS salary_increment_letter (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  request_id CHAR(36) NOT NULL,
  employee_id CHAR(36) NOT NULL,
  letter_type VARCHAR(80) NOT NULL DEFAULT 'increment_letter',
  letter_ref VARCHAR(120) DEFAULT NULL,
  template_key VARCHAR(120) DEFAULT 'salary_increment_letter',
  file_url VARCHAR(900) DEFAULT NULL,
  generated_by CHAR(36) DEFAULT NULL,
  generated_at DATETIME DEFAULT NULL,
  released_by CHAR(36) DEFAULT NULL,
  released_at DATETIME DEFAULT NULL,
  acknowledged_at DATETIME DEFAULT NULL,
  status ENUM('draft','generated','released','acknowledged','cancelled') NOT NULL DEFAULT 'draft',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY ux_increment_letter_request (request_id),
  KEY idx_increment_letter_employee (employee_id),
  CONSTRAINT fk_increment_letter_request FOREIGN KEY (request_id) REFERENCES salary_increment_request(id) ON DELETE CASCADE,
  CONSTRAINT fk_increment_letter_employee FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
