import React, { useState, useEffect } from 'react';
import { useAutoSave } from '../useAutoSave';

interface S4Props {
  token: string;
  initialData: Record<string, unknown> | null;
  saveSection: (endpoint: string, payload: Record<string, unknown>) => Promise<void>;
}

export function S4_StatutoryIds({ token: _token, initialData, saveSection }: S4Props) {
  const [form, setForm] = useState({
    epf_number: '', new_epf_number: '', uan_number: '',
    esic_number: '', pf_eligible: '', esi_eligible: '',
  });

  useEffect(() => {
    if (initialData) {
      setForm(prev => ({ ...prev, ...Object.fromEntries(Object.entries(initialData).filter(([,v]) => v != null).map(([k,v]) => [k, String(v)])) }));
    }
  }, [initialData]);

  const set = (k: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
    setForm(prev => ({ ...prev, [k]: e.target.value }));

  useAutoSave(payload => saveSection('employee-details', payload), form);

  const uanError = form.uan_number && !/^\d{12}$/.test(form.uan_number)
    ? 'UAN must be exactly 12 digits'
    : null;
  const esicError = form.esic_number && !/^\d{17}$/.test(form.esic_number)
    ? 'ESIC number must be exactly 17 digits'
    : null;

  const lbl = 'block text-xs font-semibold text-gray-600 mb-1';
  const inp = 'w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-purple-400';
  const inpErr = inp + ' border-red-300 focus:ring-red-300';
  const sel = inp;

  return (
    <div className="space-y-6">
      <h2 className="text-lg font-bold text-gray-800">Statutory IDs</h2>
      <p className="text-sm text-gray-500">Leave blank if you are a fresher or do not have existing statutory IDs. These will be assigned/generated by HR after joining.</p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className={lbl}>UAN (Universal Account Number)</label>
          <input className={uanError ? inpErr : inp} value={form.uan_number} onChange={set('uan_number')} placeholder="12-digit UAN" maxLength={12} inputMode="numeric" />
          {uanError && <p className="text-xs text-red-500 mt-1">{uanError}</p>}
        </div>
        <div>
          <label className={lbl}>PF Member ID (Old)</label>
          <input className={inp} value={form.epf_number} onChange={set('epf_number')} placeholder="XX/XXX/XXXXXXX/XXX/XXXXXXX" />
        </div>
        <div>
          <label className={lbl}>PF Member ID (New / EPFO format)</label>
          <input className={inp} value={form.new_epf_number} onChange={set('new_epf_number')} />
        </div>
        <div>
          <label className={lbl}>ESIC Beneficiary Number</label>
          <input className={esicError ? inpErr : inp} value={form.esic_number} onChange={set('esic_number')} placeholder="17-digit ESIC number" maxLength={17} inputMode="numeric" />
          {esicError && <p className="text-xs text-red-500 mt-1">{esicError}</p>}
        </div>
        <div>
          <label className={lbl}>PF Eligibility</label>
          <select className={sel} value={form.pf_eligible} onChange={set('pf_eligible')}>
            <option value="">HR will determine</option>
            <option value="yes">Yes</option>
            <option value="no">No (salary above threshold)</option>
          </select>
        </div>
        <div>
          <label className={lbl}>ESI Eligibility</label>
          <select className={sel} value={form.esi_eligible} onChange={set('esi_eligible')}>
            <option value="">HR will determine</option>
            <option value="yes">Yes</option>
            <option value="no">No (salary above threshold)</option>
          </select>
        </div>
      </div>
      <p className="text-xs text-gray-400 bg-blue-50 p-3 rounded-lg">PF/ESI eligibility is determined by HR based on your salary slab. If you opt out of PF (salary &gt; ₹15,000), provide a declaration at the time of joining.</p>
    </div>
  );
}
